num1=input("enter first number: ")
num2=input("enter second number: ")
num1=int(num1)
num2=int(num2)
Div=float(num1/num2)
print("addition: ", num1+num2)
print("subtraction: ", num1-num2)
print("Multiplication: ", num1*num2)
print("Division:", Div)